apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  selector:
    app: api

  ports:
    - name: http
      port: 5000

  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: database
spec:
  selector:
    app: db
  ports:
    - port: 5432
  type: ClusterIP
