apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
  - name: api
    image: testmailt46/simple-flask-api:version1.7
    env:
      - name: POSTGRES_HOSTNAME
        value: postgres
      - name: SQLALCHEMY_DATABASE_URI
        value: postgresql+psycopg2://test:test@db/test

---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
   - name: db
     image: postgres
     env:
      - name: POSTGRES_USER
        value: test
      - name: POSTGRES_PASSWORD
        value: test
      - name: POSTGRES_DB
        value: test
