apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
  - name: api
    image: testmailt46/simple-flask-api:version1.7

---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
   - name: postgres
     image: postgres
     env:
      - name: POSTGRES_USER
        value: test
      - name: POSTGRES_PASSWORD
        value: test
      - name: POSTGRES_DB
        value: test